# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram.xci
# IP: The module: 'adc_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram.xci
# IP: The module: 'adc_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
