set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in1[0]}]

set_property PACKAGE_PIN AA14 [get_ports {adc_in0[13]}]
set_property PACKAGE_PIN Y14 [get_ports {adc_in0[12]}]
set_property PACKAGE_PIN Y16 [get_ports {adc_in0[11]}]
set_property PACKAGE_PIN W16 [get_ports {adc_in0[10]}]
set_property PACKAGE_PIN AB17 [get_ports {adc_in0[9]}]
set_property PACKAGE_PIN AA17 [get_ports {adc_in0[8]}]
set_property PACKAGE_PIN W17 [get_ports {adc_in0[7]}]
set_property PACKAGE_PIN W18 [get_ports {adc_in0[6]}]
set_property PACKAGE_PIN W13 [get_ports {adc_in0[5]}]
set_property PACKAGE_PIN V13 [get_ports {adc_in0[4]}]
set_property PACKAGE_PIN AA13 [get_ports {adc_in0[3]}]
set_property PACKAGE_PIN Y13 [get_ports {adc_in0[2]}]
set_property PACKAGE_PIN AB15 [get_ports {adc_in0[1]}]
set_property PACKAGE_PIN AB14 [get_ports {adc_in0[0]}]
set_property PACKAGE_PIN AA18 [get_ports {adc_in1[13]}]
set_property PACKAGE_PIN AB16 [get_ports {adc_in1[12]}]
set_property PACKAGE_PIN AA16 [get_ports {adc_in1[11]}]
set_property PACKAGE_PIN AA19 [get_ports {adc_in1[10]}]
set_property PACKAGE_PIN Y19 [get_ports {adc_in1[9]}]
set_property PACKAGE_PIN AB19 [get_ports {adc_in1[8]}]
set_property PACKAGE_PIN AB20 [get_ports {adc_in1[7]}]
set_property PACKAGE_PIN AB21 [get_ports {adc_in1[6]}]
set_property PACKAGE_PIN AA21 [get_ports {adc_in1[5]}]
set_property PACKAGE_PIN AB22 [get_ports {adc_in1[4]}]
set_property PACKAGE_PIN AA22 [get_ports {adc_in1[3]}]
set_property PACKAGE_PIN Y21 [get_ports {adc_in1[2]}]
set_property PACKAGE_PIN Y20 [get_ports {adc_in1[1]}]
set_property PACKAGE_PIN W22 [get_ports {adc_in1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk1]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
# set_property IOSTANDARD LVCMOS33 [get_ports ext_trig]

set_property PACKAGE_PIN V22 [get_ports adc_clk1]
set_property PACKAGE_PIN V14 [get_ports adc_clk0]
set_property PACKAGE_PIN M19 [get_ports clk]
set_property PACKAGE_PIN J20 [get_ports rstn]
set_property PACKAGE_PIN T22 [get_ports spi_cs]
set_property PACKAGE_PIN U22 [get_ports spi_clk]
set_property PACKAGE_PIN F18 [get_ports spi_miso]
set_property PACKAGE_PIN E18 [get_ports spi_mosi]
# set_property PACKAGE_PIN <YOUR_EXT_TRIG_PIN> [get_ports ext_trig]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports ext_trig]
set_property PACKAGE_PIN C20 [get_ports ext_trig]
