# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.cache/wt [current_project]
set_property parent.project_path C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/ad9248.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/adc_ram_control.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/reg_control.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/spi_control.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/spi_reg_control.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/spi_slave.v
  C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/new/top.v
}
read_ip -quiet C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram.xci
set_property used_in_implementation false [get_files -all c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/adc_ram/adc_ram_ooc.xdc]

read_ip -quiet C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xci
set_property used_in_implementation false [get_files -all c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_board.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xdc]
set_property used_in_implementation false [get_files -all c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/constrs_1/new/test.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
