# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xci
# IP: The module: 'clk_wiz_40_96m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xci
# IP: The module: 'clk_wiz_40_96m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/FPGA_project/xc7z020clg484-1/test_adc_19.2/test_adc_19.2.srcs/sources_1/ip/clk_wiz_40_96m/clk_wiz_40_96m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_40_96m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
